{{- $tracingUrl := include "jobnik-worker-boilerplate.tracingUrl" . -}}
{{- $metricsUrl := include "jobnik-worker-boilerplate.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configmap" (include "jobnik-worker-boilerplate.fullname" .) }}
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  npm_config_cache: /tmp/
  {{- with .Values.configManagement }}
  CONFIG_NAME: {{ .name| quote }}
  CONFIG_VERSION: {{ .version | quote }}
  CONFIG_OFFLINE_MODE: {{ .offlineMode | quote }}
  CONFIG_SERVER_URL: {{ .serverUrl | quote }}
  {{- end -}}
{{- end }}
