apiVersion: v2
name: jobnik-worker-boilerplate
description: A Helm chart for jobnik-worker-boilerplate service
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
